apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.spec.destination.name }}-helm-guestbook
  namespace: argocd
  labels: 
    cluster: {{ .Values.spec.destination.name }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: {{ .Values.spec.destination.name }}
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/ribeiro-rodrigo-exemplos/argocd-example-apps/tree/master/helm-guestbook
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true 
